### ISSUE TITLE
Example does not work with node 11.3

### ISSUE THREAD

**Issue by raspyweather** [dy/image-encode#2]
the example you provide in the readme does not work 
```let encode = require('image-encode')

// create a file with chess pattern
fs.writeFileSync(
	encode([0,0,0,255, 255,255,255,255, 255,255,255,255, 0,0,0,255], [2, 2], 'png')
) 
```

I got it working by manually installing missing dependencies like is-browser, but I'm not sure whether it's the right way to do this. Probably you should fix this, since I don't know if my fix is the proper way to do this.

```
    let imageEncode = require('image-encode')
    fs.writeFileSync(`output.png`, Buffer.from(imageEncode([0,0,0,255, 255,255,255,255, 255,255,255,255, 0,0,0,255], 'png', [2, 2])));
```

**Comment by dy** [comment]
@raspyweather oh, thanks a lot! Fixed.
