### ISSUE TITLE
Suggestion: make a new npm release

### ISSUE THREAD

**Issue by sbrl** [dy/image-encode#9]
I've just received a security warning from GitHub regarding jpeg-js, one of your dependencies. However, when I cloned your repo to take a look, it has already been updated. To this end, I suggest that new release is made to push that fix out to everyone.

I'm unsure as to which version on npm though, as this repo doesn't have any Git tags or GitHub releases to cross-check.

(also, maybe the other dependencies could be updated too?)

**Comment by dy** [comment]
Ok, done, thanks!
